CREATE TABLE [dbo].[Classroom]
(
	[Id] NVARCHAR(50) UNIQUE NOT NULL DEFAULT (NEWID()),
	[TeacherId] NVARCHAR(50) NOT NULL,
	[ClassName] NVARCHAR(70) DEFAULT NULL,
	[Capacity] SMALLINT NOT NULL DEFAULT 1,
	[Price] DECIMAL(6,2) NOT NULL DEFAULT 1,
	[CommencedOn] DATETIME2(7) DEFAULT NULL,
	[Duration] TINYINT NOT NULL DEFAULT 1,
	[DurationUnit] TINYINT NOT NULL DEFAULT 0,
	[IsActive] BIT NOT NULL DEFAULT 0,
	[CreatedOn] DATETIME2(7) NOT NULL DEFAULT (GETDATE()),
	CONSTRAINT [PK_Classroom_Id] PRIMARY KEY ([Id] ASC),
	CONSTRAINT [FK_Classroom_Teacher_TeacherId] FOREIGN KEY ([TeacherId]) REFERENCES [dbo].[Teacher] ([Id]) ON DELETE CASCADE
)
