// For Paypal checkout
export const PAYPAL_CHECKOUT_REQUEST_SENT = 'PAYPAL_CHECKOUT_REQUEST_SENT';
export type T_PAYPAL_CHECKOUT_REQUEST_SENT = typeof PAYPAL_CHECKOUT_REQUEST_SENT;

export const PAYPAL_CHECKOUT_REQUEST_SUCCESS = 'PAYPAL_CHECKOUT_REQUEST_SUCCESS';
export type T_PAYPAL_CHECKOUT_REQUEST_SUCCESS = typeof PAYPAL_CHECKOUT_REQUEST_SUCCESS;

export const PAYPAL_CHECKOUT_REQUEST_FAILED = 'PAYPAL_CHECKOUT_REQUEST_FAILED';
export type T_PAYPAL_CHECKOUT_REQUEST_FAILED = typeof PAYPAL_CHECKOUT_REQUEST_FAILED;

// For GooglePay checkout
export const GOOGLE_CHECKOUT_REQUEST_SENT = 'GOOGLE_CHECKOUT_REQUEST_SENT';
export type T_GOOGLE_CHECKOUT_REQUEST_SENT = typeof GOOGLE_CHECKOUT_REQUEST_SENT;

export const GOOGLE_CHECKOUT_REQUEST_SUCCESS = 'GOOGLE_CHECKOUT_REQUEST_SUCCESS';
export type T_GOOGLE_CHECKOUT_REQUEST_SUCCESS = typeof GOOGLE_CHECKOUT_REQUEST_SUCCESS;

export const GOOGLE_CHECKOUT_REQUEST_FAILED = 'GOOGLE_CHECKOUT_REQUEST_FAILED';
export type T_GOOGLE_CHECKOUT_REQUEST_FAILED = typeof GOOGLE_CHECKOUT_REQUEST_FAILED;

// For Card checkout
export const CARD_CHECKOUT_REQUEST_SENT = 'CARD_CHECKOUT_REQUEST_SENT';
export type T_CARD_CHECKOUT_REQUEST_SENT = typeof CARD_CHECKOUT_REQUEST_SENT;

export const CARD_CHECKOUT_REQUEST_SUCCESS = 'CARD_CHECKOUT_REQUEST_SUCCESS';
export type T_CARD_CHECKOUT_REQUEST_SUCCESS = typeof CARD_CHECKOUT_REQUEST_SUCCESS;

export const CARD_CHECKOUT_REQUEST_FAILED = 'CARD_CHECKOUT_REQUEST_FAILED';
export type T_CARD_CHECKOUT_REQUEST_FAILED = typeof CARD_CHECKOUT_REQUEST_FAILED;