// To get classroom contents when page load
export const GET_CLASSROOM_CONTENTS_REQUEST_SENT = 'GET_CLASSROOM_CONTENTS_REQUEST_SENT';
export type T_GET_CLASSROOM_CONTENTS_REQUEST_SENT = typeof GET_CLASSROOM_CONTENTS_REQUEST_SENT;

export const GET_CLASSROOM_CONTENTS_REQUEST_SUCCESS = 'GET_CLASSROOM_CONTENTS_REQUEST_SUCCESS';
export type T_GET_CLASSROOM_CONTENTS_REQUEST_SUCCESS = typeof GET_CLASSROOM_CONTENTS_REQUEST_SUCCESS;

export const GET_CLASSROOM_CONTENTS_REQUEST_FAILED = 'GET_CLASSROOM_CONTENTS_REQUEST_FAILED';
export type T_GET_CLASSROOM_CONTENTS_REQUEST_FAILED = typeof GET_CLASSROOM_CONTENTS_REQUEST_FAILED;

// To upload files for a classroom
export const ADD_FILES_TO_CLASSROOM_REQUEST_SENT = 'ADD_FILES_TO_CLASSROOM_REQUEST_SENT';
export type T_ADD_FILES_TO_CLASSROOM_REQUEST_SENT = typeof ADD_FILES_TO_CLASSROOM_REQUEST_SENT;

export const ADD_FILES_TO_CLASSROOM_REQUEST_SUCCESS = 'ADD_FILES_TO_CLASSROOM_REQUEST_SUCCESS';
export type T_ADD_FILES_TO_CLASSROOM_REQUEST_SUCCESS = typeof ADD_FILES_TO_CLASSROOM_REQUEST_SUCCESS;

export const ADD_FILES_TO_CLASSROOM_REQUEST_FAILED = 'ADD_FILES_TO_CLASSROOM_REQUEST_FAILED';
export type T_ADD_FILES_TO_CLASSROOM_REQUEST_FAILED = typeof ADD_FILES_TO_CLASSROOM_REQUEST_FAILED;

// To update and/or remove files for a classroom
export const UPDATE_OR_REMOVE_FILES_REQUEST_SENT = 'UPDATE_OR_REMOVE_FILES_REQUEST_SENT';
export type T_UPDATE_OR_REMOVE_FILES_REQUEST_SENT = typeof UPDATE_OR_REMOVE_FILES_REQUEST_SENT;

export const UPDATE_OR_REMOVE_FILES_REQUEST_SUCCESS = 'UPDATE_OR_REMOVE_FILES_REQUEST_SUCCESS';
export type T_UPDATE_OR_REMOVE_FILES_REQUEST_SUCCESS = typeof UPDATE_OR_REMOVE_FILES_REQUEST_SUCCESS;

export const UPDATE_OR_REMOVE_FILES_REQUEST_FAILED = 'UPDATE_OR_REMOVE_FILES_REQUEST_FAILED';
export type T_UPDATE_OR_REMOVE_FILES_REQUEST_FAILED = typeof UPDATE_OR_REMOVE_FILES_REQUEST_FAILED;

// To add rich-text content for a classroom
export const ADD_RICH_CONTENT_REQUEST_SENT = 'ADD_RICH_CONTENT_REQUEST_SENT';
export type T_ADD_RICH_CONTENT_REQUEST_SENT = typeof ADD_RICH_CONTENT_REQUEST_SENT;

export const ADD_RICH_CONTENT_REQUEST_SUCCESS = 'ADD_RICH_CONTENT_REQUEST_SUCCESS';
export type T_ADD_RICH_CONTENT_REQUEST_SUCCESS = typeof ADD_RICH_CONTENT_REQUEST_SUCCESS;

export const ADD_RICH_CONTENT_REQUEST_FAILED = 'ADD_RICH_CONTENT_REQUEST_FAILED';
export type T_ADD_RICH_CONTENT_REQUEST_FAILED = typeof ADD_RICH_CONTENT_REQUEST_FAILED;

// To upload files for importing rich-text content
export const IMPORT_RICH_CONTENT_REQUEST_SENT = 'IMPORT_RICH_CONTENT_REQUEST_SENT';
export type T_IMPORT_RICH_CONTENT_REQUEST_SENT = typeof IMPORT_RICH_CONTENT_REQUEST_SENT;

export const IMPORT_RICH_CONTENT_REQUEST_SUCCESS = 'IMPORT_RICH_CONTENT_REQUEST_SUCCESS';
export type T_IMPORT_RICH_CONTENT_REQUEST_SUCCESS = typeof IMPORT_RICH_CONTENT_REQUEST_SUCCESS;

export const IMPORT_RICH_CONTENT_REQUEST_FAILED = 'IMPORT_RICH_CONTENT_REQUEST_FAILED';
export type T_IMPORT_RICH_CONTENT_REQUEST_FAILED = typeof IMPORT_RICH_CONTENT_REQUEST_FAILED;

// To update rich-text content
export const UPDATE_RICH_CONTENT_REQUEST_SENT = 'UPDATE_RICH_CONTENT_REQUEST_SENT';
export type T_UPDATE_RICH_CONTENT_REQUEST_SENT = typeof UPDATE_RICH_CONTENT_REQUEST_SENT;

export const UPDATE_RICH_CONTENT_REQUEST_SUCCESS = 'UPDATE_RICH_CONTENT_REQUEST_SUCCESS';
export type T_UPDATE_RICH_CONTENT_REQUEST_SUCCESS = typeof UPDATE_RICH_CONTENT_REQUEST_SUCCESS;

export const UPDATE_RICH_CONTENT_REQUEST_FAILED = 'UPDATE_RICH_CONTENT_REQUEST_FAILED';
export type T_UPDATE_RICH_CONTENT_REQUEST_FAILED = typeof UPDATE_RICH_CONTENT_REQUEST_FAILED;