// To export classrooms
export const EXPORT_CLASSROOMS_REQUEST_SENT = 'EXPORT_CLASSROOMS_REQUEST_SENT';
export type T_EXPORT_CLASSROOMS_REQUEST_SENT = typeof EXPORT_CLASSROOMS_REQUEST_SENT;

export const EXPORT_CLASSROOMS_REQUEST_SUCCESS = 'EXPORT_CLASSROOMS_REQUEST_SUCCESS';
export type T_EXPORT_CLASSROOMS_REQUEST_SUCCESS = typeof EXPORT_CLASSROOMS_REQUEST_SUCCESS;

export const EXPORT_CLASSROOMS_REQUEST_FAILED = 'EXPORT_CLASSROOMS_REQUEST_FAILED';
export type T_EXPORT_CLASSROOMS_REQUEST_FAILED = typeof EXPORT_CLASSROOMS_REQUEST_FAILED;

// To export students in classrooms
export const EXPORT_STUDENTS_REQUEST_SENT = 'EXPORT_STUDENTS_REQUEST_SENT';
export type T_EXPORT_STUDENTS_REQUEST_SENT = typeof EXPORT_STUDENTS_REQUEST_SENT;

export const EXPORT_STUDENTS_REQUEST_SUCCESS = 'EXPORT_STUDENTS_REQUEST_SUCCESS';
export type T_EXPORT_STUDENTS_REQUEST_SUCCESS = typeof EXPORT_STUDENTS_REQUEST_SUCCESS;

export const EXPORT_STUDENTS_REQUEST_FAILED = 'EXPORT_STUDENTS_REQUEST_FAILED';
export type T_EXPORT_STUDENTS_REQUEST_FAILED = typeof EXPORT_STUDENTS_REQUEST_FAILED;

// To get the progress of import schedules
export const GET_IMPORT_SCHEDULES_PROGRESS_REQUEST_SENT = 'GET_IMPORT_SCHEDULES_PROGRESS_REQUEST_SENT';
export type T_GET_IMPORT_SCHEDULES_PROGRESS_REQUEST_SENT = typeof GET_IMPORT_SCHEDULES_PROGRESS_REQUEST_SENT;

export const GET_IMPORT_SCHEDULES_PROGRESS_REQUEST_SUCCESS = 'GET_IMPORT_SCHEDULES_PROGRESS_REQUEST_SUCCESS';
export type T_GET_IMPORT_SCHEDULES_PROGRESS_REQUEST_SUCCESS = typeof GET_IMPORT_SCHEDULES_PROGRESS_REQUEST_SUCCESS;

export const GET_IMPORT_SCHEDULES_PROGRESS_REQUEST_FAILED = 'GET_IMPORT_SCHEDULES_PROGRESS_REQUEST_FAILED';
export type T_GET_IMPORT_SCHEDULES_PROGRESS_REQUEST_FAILED = typeof GET_IMPORT_SCHEDULES_PROGRESS_REQUEST_FAILED;