// When app launches
export const LOAD_AUTH_DATA = 'LOAD_AUTH_DATA';
export type T_LOAD_AUTH_DATA = typeof LOAD_AUTH_DATA;

// When sign-in success
export const AUTHENTICATED = 'AUTHENTICATED';
export type T_AUTHENTICATED = typeof AUTHENTICATED;

// When sign-out success
export const NO_AUTHENTICATION = 'NO_AUTHENTICATION';
export type T_NO_AUTHENTICATION = typeof NO_AUTHENTICATION;

// Constants for handling logging-in
export const AUTHENTICATION_BEGIN = 'AUTHENTICATION_BEGIN';
export type T_AUTHENTICATION_BEGIN = typeof AUTHENTICATION_BEGIN;

export const AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS';
export type T_AUTHENTICATION_SUCCESS = typeof AUTHENTICATION_SUCCESS;

export const AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED';
export type T_AUTHENTICATION_FAILED = typeof AUTHENTICATION_FAILED;

// Constants for handling registration
export const REGISTRATION_REQUEST_SENT = 'REGISTRATION_REQUEST_SENT';
export type T_REGISTRATION_REQUEST_SENT = typeof REGISTRATION_REQUEST_SENT;

export const REGISTRATION_REQUEST_SUCCESS = 'REGISTRATION_REQUEST_SUCCESS';
export type T_REGISTRATION_REQUEST_SUCCESS = typeof REGISTRATION_REQUEST_SUCCESS;

export const REGISTRATION_REQUEST_FAILED = 'REGISTRATION_REQUEST_FAILED';
export type T_REGISTRATION_REQUEST_FAILED = typeof REGISTRATION_REQUEST_FAILED;

// Constants for handling sign-out
export const SIGNOUT_REQUEST_SENT = 'SIGNOUT_REQUEST_SENT';
export type T_SIGNOUT_REQUEST_SENT = typeof SIGNOUT_REQUEST_SENT;

export const SIGNOUT_REQUEST_SUCCESS = 'SIGNOUT_REQUEST_SUCCESS';
export type T_SIGNOUT_REQUEST_SUCCESS = typeof SIGNOUT_REQUEST_SUCCESS;

export const SIGNOUT_REQUEST_FAILED = 'SIGNOUT_REQUEST_FAILED';
export type T_SIGNOUT_REQUEST_FAILED = typeof SIGNOUT_REQUEST_FAILED;