// To get student details
export const GET_STUDENT_DETAIL_REQUEST_SENT = 'GET_STUDENT_DETAIL_REQUEST_SENT';
export type T_GET_STUDENT_DETAIL_REQUEST_SENT = typeof GET_STUDENT_DETAIL_REQUEST_SENT;

export const GET_STUDENT_DETAIL_REQUEST_SUCCESS = 'GET_STUDENT_DETAIL_REQUEST_SUCCESS';
export type T_GET_STUDENT_DETAIL_REQUEST_SUCCESS = typeof GET_STUDENT_DETAIL_REQUEST_SUCCESS;

export const GET_STUDENT_DETAIL_REQUEST_FAILED = 'GET_STUDENT_DETAIL_REQUEST_FAILED';
export type T_GET_STUDENT_DETAIL_REQUEST_FAILED = typeof GET_STUDENT_DETAIL_REQUEST_FAILED;

// To get teacher details
export const GET_TEACHER_DETAIL_REQUEST_SENT = 'GET_TEACHER_DETAIL_REQUEST_SENT';
export type T_GET_TEACHER_DETAIL_REQUEST_SENT = typeof GET_TEACHER_DETAIL_REQUEST_SENT;

export const GET_TEACHER_DETAIL_REQUEST_SUCCESS = 'GET_TEACHER_DETAIL_REQUEST_SUCCESS';
export type T_GET_TEACHER_DETAIL_REQUEST_SUCCESS = typeof GET_TEACHER_DETAIL_REQUEST_SUCCESS;

export const GET_TEACHER_DETAIL_REQUEST_FAILED = 'GET_TEACHER_DETAIL_REQUEST_FAILED';
export type T_GET_TEACHER_DETAIL_REQUEST_FAILED = typeof GET_TEACHER_DETAIL_REQUEST_FAILED;

// To confirm phone number
export const CONFIRM_PHONE_NUMBER_REQUEST_SENT = 'CONFIRM_PHONE_NUMBER_REQUEST_SENT';
export type T_CONFIRM_PHONE_NUMBER_REQUEST_SENT = typeof CONFIRM_PHONE_NUMBER_REQUEST_SENT;

export const CONFIRM_PHONE_NUMBER_REQUEST_SUCCESS = 'CONFIRM_PHONE_NUMBER_REQUEST_SUCCESS';
export type T_CONFIRM_PHONE_NUMBER_REQUEST_SUCCESS = typeof CONFIRM_PHONE_NUMBER_REQUEST_SUCCESS;

export const CONFIRM_PHONE_NUMBER_REQUEST_FAILED = 'CONFIRM_PHONE_NUMBER_REQUEST_FAILED';
export type T_CONFIRM_PHONE_NUMBER_REQUEST_FAILED = typeof CONFIRM_PHONE_NUMBER_REQUEST_FAILED;

// To request new SMS token for confirming phone number
export const NEW_SMS_TOKEN_REQUEST_SENT = 'NEW_SMS_TOKEN_REQUEST_SENT';
export type T_NEW_SMS_TOKEN_REQUEST_SENT = typeof NEW_SMS_TOKEN_REQUEST_SENT;

export const NEW_SMS_TOKEN_REQUEST_SUCCESS = 'NEW_SMS_TOKEN_REQUEST_SUCCESS';
export type T_NEW_SMS_TOKEN_REQUEST_SUCCESS = typeof NEW_SMS_TOKEN_REQUEST_SUCCESS;

export const NEW_SMS_TOKEN_REQUEST_FAILED = 'NEW_SMS_TOKEN_REQUEST_FAILED';
export type T_NEW_SMS_TOKEN_REQUEST_FAILED = typeof NEW_SMS_TOKEN_REQUEST_FAILED;

// To remove phone number
export const REMOVE_PHONE_NUMBER_REQUEST_SENT = 'REMOVE_PHONE_NUMBER_REQUEST_SENT';
export type T_REMOVE_PHONE_NUMBER_REQUEST_SENT = typeof REMOVE_PHONE_NUMBER_REQUEST_SENT;

export const REMOVE_PHONE_NUMBER_REQUEST_SUCCESS = 'REMOVE_PHONE_NUMBER_REQUEST_SUCCESS';
export type T_REMOVE_PHONE_NUMBER_REQUEST_SUCCESS = typeof REMOVE_PHONE_NUMBER_REQUEST_SUCCESS;

export const REMOVE_PHONE_NUMBER_REQUEST_FAILED = 'REMOVE_PHONE_NUMBER_REQUEST_FAILED';
export type T_REMOVE_PHONE_NUMBER_REQUEST_FAILED = typeof REMOVE_PHONE_NUMBER_REQUEST_FAILED;

// To add phone number
export const ADD_PHONE_NUMBER_REQUEST_SENT = 'ADD_PHONE_NUMBER_REQUEST_SENT';
export type T_ADD_PHONE_NUMBER_REQUEST_SENT = typeof ADD_PHONE_NUMBER_REQUEST_SENT;

export const ADD_PHONE_NUMBER_REQUEST_SUCCESS = 'ADD_PHONE_NUMBER_REQUEST_SUCCESS';
export type T_ADD_PHONE_NUMBER_REQUEST_SUCCESS = typeof ADD_PHONE_NUMBER_REQUEST_SUCCESS;

export const ADD_PHONE_NUMBER_REQUEST_FAILED = 'ADD_PHONE_NUMBER_REQUEST_FAILED';
export type T_ADD_PHONE_NUMBER_REQUEST_FAILED = typeof ADD_PHONE_NUMBER_REQUEST_FAILED;

// To enable or renew TFA
export const ENABLE_RENEW_TFA_REQUEST_SENT = 'ENABLE_RENEW_TFA_REQUEST_SENT';
export type T_ENABLE_RENEW_TFA_REQUEST_SENT = typeof ENABLE_RENEW_TFA_REQUEST_SENT;

export const ENABLE_RENEW_TFA_REQUEST_SUCCESS = 'ENABLE_RENEW_TFA_REQUEST_SUCCESS';
export type T_ENABLE_RENEW_TFA_REQUEST_SUCCESS = typeof ENABLE_RENEW_TFA_REQUEST_SUCCESS;

export const ENABLE_RENEW_TFA_REQUEST_FAILED = 'ENABLE_RENEW_TFA_REQUEST_FAILED';
export type T_ENABLE_RENEW_TFA_REQUEST_FAILED = typeof ENABLE_RENEW_TFA_REQUEST_FAILED;

// To disable TFA
export const DISABLE_TFA_REQUEST_SENT = 'DISABLE_TFA_REQUEST_SENT';
export type T_DISABLE_TFA_REQUEST_SENT = typeof DISABLE_TFA_REQUEST_SENT;

export const DISABLE_TFA_REQUEST_SUCCESS = 'DISABLE_TFA_REQUEST_SUCCESS';
export type T_DISABLE_TFA_REQUEST_SUCCESS = typeof DISABLE_TFA_REQUEST_SUCCESS;

export const DISABLE_TFA_REQUEST_FAILED = 'DISABLE_TFA_REQUEST_FAILED';
export type T_DISABLE_TFA_REQUEST_FAILED = typeof DISABLE_TFA_REQUEST_FAILED;

// To update student details
export const UPDATE_STUDENT_DETAIL_REQUEST_SENT = 'UPDATE_STUDENT_DETAIL_REQUEST_SENT';
export type T_UPDATE_STUDENT_DETAIL_REQUEST_SENT = typeof UPDATE_STUDENT_DETAIL_REQUEST_SENT;

export const UPDATE_STUDENT_DETAIL_REQUEST_SUCCESS = 'UPDATE_STUDENT_DETAIL_REQUEST_SUCCESS';
export type T_UPDATE_STUDENT_DETAIL_REQUEST_SUCCESS = typeof UPDATE_STUDENT_DETAIL_REQUEST_SUCCESS;

export const UPDATE_STUDENT_DETAIL_REQUEST_FAILED = 'UPDATE_STUDENT_DETAIL_REQUEST_FAILED';
export type T_UPDATE_STUDENT_DETAIL_REQUEST_FAILED = typeof UPDATE_STUDENT_DETAIL_REQUEST_FAILED;

// To update teacher details
export const UPDATE_TEACHER_DETAIL_REQUEST_SENT = 'UPDATE_TEACHER_DETAIL_REQUEST_SENT';
export type T_UPDATE_TEACHER_DETAIL_REQUEST_SENT = typeof UPDATE_TEACHER_DETAIL_REQUEST_SENT;

export const UPDATE_TEACHER_DETAIL_REQUEST_SUCCESS = 'UPDATE_TEACHER_DETAIL_REQUEST_SUCCESS';
export type T_UPDATE_TEACHER_DETAIL_REQUEST_SUCCESS = typeof UPDATE_TEACHER_DETAIL_REQUEST_SUCCESS;

export const UPDATE_TEACHER_DETAIL_REQUEST_FAILED = 'UPDATE_TEACHER_DETAIL_REQUEST_FAILED';
export type T_UPDATE_TEACHER_DETAIL_REQUEST_FAILED = typeof UPDATE_TEACHER_DETAIL_REQUEST_FAILED;