// To get the statistics
export const GET_STATISTICS_RESULTS_REQUEST_SENT = 'GET_STATISTICS_RESULTS_REQUEST_SENT';
export type T_GET_STATISTICS_RESULTS_REQUEST_SENT = typeof GET_STATISTICS_RESULTS_REQUEST_SENT;

export const GET_STATISTICS_RESULTS_REQUEST_SUCCESS = 'GET_STATISTICS_RESULTS_REQUEST_SUCCESS';
export type T_GET_STATISTICS_RESULTS_REQUEST_SUCCESS = typeof GET_STATISTICS_RESULTS_REQUEST_SUCCESS;

export const GET_STATISTICS_RESULTS_REQUEST_FAILED = 'GET_STATISTICS_RESULTS_REQUEST_FAILED';
export type T_GET_STATISTICS_RESULTS_REQUEST_FAILED = typeof GET_STATISTICS_RESULTS_REQUEST_FAILED;

// To trigger Mapper step
export const TRIGGER_MAPPER_REQUEST_SENT = 'TRIGGER_MAPPER_REQUEST_SENT';
export type T_TRIGGER_MAPPER_REQUEST_SENT = typeof TRIGGER_MAPPER_REQUEST_SENT;

export const TRIGGER_MAPPER_REQUEST_SUCCESS = 'TRIGGER_MAPPER_REQUEST_SUCCESS';
export type T_TRIGGER_MAPPER_REQUEST_SUCCESS = typeof TRIGGER_MAPPER_REQUEST_SUCCESS;

export const TRIGGER_MAPPER_REQUEST_FAILED = 'TRIGGER_MAPPER_REQUEST_FAILED';
export type T_TRIGGER_MAPPER_REQUEST_FAILED = typeof TRIGGER_MAPPER_REQUEST_FAILED;

// To trigger Reducer step
export const TRIGGER_REDUCER_REQUEST_SENT = 'TRIGGER_REDUCER_REQUEST_SENT';
export type T_TRIGGER_REDUCER_REQUEST_SENT = typeof TRIGGER_REDUCER_REQUEST_SENT;

export const TRIGGER_REDUCER_REQUEST_SUCCESS = 'TRIGGER_REDUCER_REQUEST_SUCCESS';
export type T_TRIGGER_REDUCER_REQUEST_SUCCESS = typeof TRIGGER_REDUCER_REQUEST_SUCCESS;

export const TRIGGER_REDUCER_REQUEST_FAILED = 'TRIGGER_REDUCER_REQUEST_FAILED';
export type T_TRIGGER_REDUCER_REQUEST_FAILED = typeof TRIGGER_REDUCER_REQUEST_FAILED;