// To get all classrooms for a teacher
export const GET_TEACHER_CLASSROOMS_REQUEST_SENT = 'GET_TEACHER_CLASSROOMS_REQUEST_SENT';
export type T_GET_TEACHER_CLASSROOMS_REQUEST_SENT = typeof GET_TEACHER_CLASSROOMS_REQUEST_SENT;

export const GET_TEACHER_CLASSROOMS_REQUEST_SUCCESS = 'GET_TEACHER_CLASSROOMS_REQUEST_SUCCESS';
export type T_GET_TEACHER_CLASSROOMS_REQUEST_SUCCESS = typeof GET_TEACHER_CLASSROOMS_REQUEST_SUCCESS;

export const GET_TEACHER_CLASSROOMS_REQUEST_FAILED = 'GET_TEACHER_CLASSROOMS_REQUEST_FAILED';
export type T_GET_TEACHER_CLASSROOMS_REQUEST_FAILED = typeof GET_TEACHER_CLASSROOMS_REQUEST_FAILED;

// To remove/delete a classroom
export const REMOVE_CLASSROOMS_REQUEST_SENT = 'REMOVE_CLASSROOMS_REQUEST_SENT';
export type T_REMOVE_CLASSROOMS_REQUEST_SENT = typeof REMOVE_CLASSROOMS_REQUEST_SENT;

export const REMOVE_CLASSROOMS_REQUEST_SUCCESS = 'REMOVE_CLASSROOMS_REQUEST_SUCCESS';
export type T_REMOVE_CLASSROOMS_REQUEST_SUCCESS = typeof REMOVE_CLASSROOMS_REQUEST_SUCCESS;

export const REMOVE_CLASSROOMS_REQUEST_FAILED = 'REMOVE_CLASSROOMS_REQUEST_FAILED';
export type T_REMOVE_CLASSROOMS_REQUEST_FAILED = typeof REMOVE_CLASSROOMS_REQUEST_FAILED;

// To mark a classroom as completed
export const COMPLETED_CLASSROOMS_REQUEST_SENT = 'COMPLETED_CLASSROOMS_REQUEST_SENT';
export type T_COMPLETED_CLASSROOMS_REQUEST_SENT = typeof COMPLETED_CLASSROOMS_REQUEST_SENT;

export const COMPLETED_CLASSROOMS_REQUEST_SUCCESS = 'COMPLETED_CLASSROOMS_REQUEST_SUCCESS';
export type T_COMPLETED_CLASSROOMS_REQUEST_SUCCESS = typeof COMPLETED_CLASSROOMS_REQUEST_SUCCESS;

export const COMPLETED_CLASSROOMS_REQUEST_FAILED = 'COMPLETED_CLASSROOMS_REQUEST_FAILED';
export type T_COMPLETED_CLASSROOMS_REQUEST_FAILED = typeof COMPLETED_CLASSROOMS_REQUEST_FAILED;

// To get classroom details (exclude classroom contents)
export const GET_CLASSROOM_DETAILS_REQUEST_SENT = 'GET_CLASSROOM_DETAILS_REQUEST_SENT';
export type T_GET_CLASSROOM_DETAILS_REQUEST_SENT = typeof GET_CLASSROOM_DETAILS_REQUEST_SENT;

export const GET_CLASSROOM_DETAILS_REQUEST_SUCCESS = 'GET_CLASSROOM_DETAILS_REQUEST_SUCCESS';
export type T_GET_CLASSROOM_DETAILS_REQUEST_SUCCESS = typeof GET_CLASSROOM_DETAILS_REQUEST_SUCCESS;

export const GET_CLASSROOM_DETAILS_REQUEST_FAILED = 'GET_CLASSROOM_DETAILS_REQUEST_FAILED';
export type T_GET_CLASSROOM_DETAILS_REQUEST_FAILED = typeof GET_CLASSROOM_DETAILS_REQUEST_FAILED;