// To get all classrooms for a teacher
export const GET_TEACHER_CLASSROOMS_REQUEST_SENT = 'GET_TEACHER_CLASSROOMS_REQUEST_SENT';
export type T_GET_TEACHER_CLASSROOMS_REQUEST_SENT = typeof GET_TEACHER_CLASSROOMS_REQUEST_SENT;

export const GET_TEACHER_CLASSROOMS_REQUEST_SUCCESS = 'GET_TEACHER_CLASSROOMS_REQUEST_SUCCESS';
export type T_GET_TEACHER_CLASSROOMS_REQUEST_SUCCESS = typeof GET_TEACHER_CLASSROOMS_REQUEST_SUCCESS;

export const GET_TEACHER_CLASSROOMS_REQUEST_FAILED = 'GET_TEACHER_CLASSROOMS_REQUEST_FAILED';
export type T_GET_TEACHER_CLASSROOMS_REQUEST_FAILED = typeof GET_TEACHER_CLASSROOMS_REQUEST_FAILED;

// To remove/delete a classroom
export const REMOVE_CLASSROOM_REQUEST_SENT = 'REMOVE_CLASSROOM_REQUEST_SENT';
export type T_REMOVE_CLASSROOM_REQUEST_SENT = typeof REMOVE_CLASSROOM_REQUEST_SENT;

export const REMOVE_CLASSROOM_REQUEST_SUCCESS = 'REMOVE_CLASSROOM_REQUEST_SUCCESS';
export type T_REMOVE_CLASSROOM_REQUEST_SUCCESS = typeof REMOVE_CLASSROOM_REQUEST_SUCCESS;

export const REMOVE_CLASSROOM_REQUEST_FAILED = 'REMOVE_CLASSROOM_REQUEST_FAILED';
export type T_REMOVE_CLASSROOM_REQUEST_FAILED = typeof REMOVE_CLASSROOM_REQUEST_FAILED;

// To mark a classroom as completed
export const COMPLETED_CLASSROOM_REQUEST_SENT = 'COMPLETED_CLASSROOM_REQUEST_SENT';
export type T_COMPLETED_CLASSROOM_REQUEST_SENT = typeof COMPLETED_CLASSROOM_REQUEST_SENT;

export const COMPLETED_CLASSROOM_REQUEST_SUCCESS = 'COMPLETED_CLASSROOM_REQUEST_SUCCESS';
export type T_COMPLETED_CLASSROOM_REQUEST_SUCCESS = typeof COMPLETED_CLASSROOM_REQUEST_SUCCESS;

export const COMPLETED_CLASSROOM_REQUEST_FAILED = 'COMPLETED_CLASSROOM_REQUEST_FAILED';
export type T_COMPLETED_CLASSROOM_REQUEST_FAILED = typeof COMPLETED_CLASSROOM_REQUEST_FAILED;

// To get classroom details (exclude classroom contents)
export const GET_CLASSROOM_DETAILS_REQUEST_SENT = 'GET_CLASSROOM_DETAILS_REQUEST_SENT';
export type T_GET_CLASSROOM_DETAILS_REQUEST_SENT = typeof GET_CLASSROOM_DETAILS_REQUEST_SENT;

export const GET_CLASSROOM_DETAILS_REQUEST_SUCCESS = 'GET_CLASSROOM_DETAILS_REQUEST_SUCCESS';
export type T_GET_CLASSROOM_DETAILS_REQUEST_SUCCESS = typeof GET_CLASSROOM_DETAILS_REQUEST_SUCCESS;

export const GET_CLASSROOM_DETAILS_REQUEST_FAILED = 'GET_CLASSROOM_DETAILS_REQUEST_FAILED';
export type T_GET_CLASSROOM_DETAILS_REQUEST_FAILED = typeof GET_CLASSROOM_DETAILS_REQUEST_FAILED;

// To create new classroom
export const CREATE_CLASSROOM_REQUEST_SENT = 'CREATE_CLASSROOM_REQUEST_SENT';
export type T_CREATE_CLASSROOM_REQUEST_SENT = typeof CREATE_CLASSROOM_REQUEST_SENT;

export const CREATE_CLASSROOM_REQUEST_SUCCESS = 'CREATE_CLASSROOM_REQUEST_SUCCESS';
export type T_CREATE_CLASSROOM_REQUEST_SUCCESS = typeof CREATE_CLASSROOM_REQUEST_SUCCESS;

export const CREATE_CLASSROOM_REQUEST_FAILED = 'CREATE_CLASSROOM_REQUEST_FAILED';
export type T_CREATE_CLASSROOM_REQUEST_FAILED = typeof CREATE_CLASSROOM_REQUEST_FAILED;

// To update a classroom
export const UPDATE_CLASSROOM_REQUEST_SENT = 'UPDATE_CLASSROOM_REQUEST_SENT';
export type T_UPDATE_CLASSROOM_REQUEST_SENT = typeof UPDATE_CLASSROOM_REQUEST_SENT;

export const UPDATE_CLASSROOM_REQUEST_SUCCESS = 'UPDATE_CLASSROOM_REQUEST_SUCCESS';
export type T_UPDATE_CLASSROOM_REQUEST_SUCCESS = typeof UPDATE_CLASSROOM_REQUEST_SUCCESS;

export const UPDATE_CLASSROOM_REQUEST_FAILED = 'UPDATE_CLASSROOM_REQUEST_FAILED';
export type T_UPDATE_CLASSROOM_REQUEST_FAILED = typeof UPDATE_CLASSROOM_REQUEST_FAILED;

// To import classrooms by uploading JSON file
export const UPLOAD_JSON_CLASSROOMS_FILE_REQUEST_SENT = 'UPLOAD_JSON_CLASSROOMS_FILE_REQUEST_SENT';
export type T_UPLOAD_JSON_CLASSROOMS_FILE_REQUEST_SENT = typeof UPLOAD_JSON_CLASSROOMS_FILE_REQUEST_SENT;

export const UPLOAD_JSON_CLASSROOMS_FILE_REQUEST_SUCCESS = 'UPLOAD_JSON_CLASSROOMS_FILE_REQUEST_SUCCESS';
export type T_UPLOAD_JSON_CLASSROOMS_FILE_REQUEST_SUCCESS = typeof UPLOAD_JSON_CLASSROOMS_FILE_REQUEST_SUCCESS;

export const UPLOAD_JSON_CLASSROOMS_FILE_REQUEST_FAILED = 'UPLOAD_JSON_CLASSROOMS_FILE_REQUEST_FAILED';
export type T_UPLOAD_JSON_CLASSROOMS_FILE_REQUEST_FAILED = typeof UPLOAD_JSON_CLASSROOMS_FILE_REQUEST_FAILED;

// To get all classrooms for browsing by student
export const GET_ALL_CLASSROOMS_REQUEST_SENT = 'GET_ALL_CLASSROOMS_REQUEST_SENT';
export type T_GET_ALL_CLASSROOMS_REQUEST_SENT = typeof GET_ALL_CLASSROOMS_REQUEST_SENT;

export const GET_ALL_CLASSROOMS_REQUEST_SUCCESS = 'GET_ALL_CLASSROOMS_REQUEST_SUCCESS';
export type T_GET_ALL_CLASSROOMS_REQUEST_SUCCESS = typeof GET_ALL_CLASSROOMS_REQUEST_SUCCESS;

export const GET_ALL_CLASSROOMS_REQUEST_FAILED = 'GET_ALL_CLASSROOMS_REQUEST_FAILED';
export type T_GET_ALL_CLASSROOMS_REQUEST_FAILED = typeof GET_ALL_CLASSROOMS_REQUEST_FAILED;