// To get all enrolments for a student
export const GET_STUDENT_ENROLMENTS_REQUEST_SENT = 'GET_STUDENT_ENROLMENTS_REQUEST_SENT';
export type T_GET_STUDENT_ENROLMENTS_REQUEST_SENT = typeof GET_STUDENT_ENROLMENTS_REQUEST_SENT;

export const GET_STUDENT_ENROLMENTS_REQUEST_SUCCESS = 'GET_STUDENT_ENROLMENTS_REQUEST_SUCCESS';
export type T_GET_STUDENT_ENROLMENTS_REQUEST_SUCCESS = typeof GET_STUDENT_ENROLMENTS_REQUEST_SUCCESS;

export const GET_STUDENT_ENROLMENTS_REQUEST_FAILED = 'GET_STUDENT_ENROLMENTS_REQUEST_FAILED';
export type T_GET_STUDENT_ENROLMENTS_REQUEST_FAILED = typeof GET_STUDENT_ENROLMENTS_REQUEST_FAILED;

// To enrol into a classroom
export const ENROL_INTO_CLASSROOM_REQUEST_SENT = 'ENROL_INTO_CLASSROOM_REQUEST_SENT';
export type T_ENROL_INTO_CLASSROOM_REQUEST_SENT = typeof ENROL_INTO_CLASSROOM_REQUEST_SENT;

export const ENROL_INTO_CLASSROOM_REQUEST_SUCCESS = 'ENROL_INTO_CLASSROOM_REQUEST_SUCCESS';
export type T_ENROL_INTO_CLASSROOM_REQUEST_SUCCESS = typeof ENROL_INTO_CLASSROOM_REQUEST_SUCCESS;

export const ENROL_INTO_CLASSROOM_REQUEST_FAILED = 'ENROL_INTO_CLASSROOM_REQUEST_FAILED';
export type T_ENROL_INTO_CLASSROOM_REQUEST_FAILED = typeof ENROL_INTO_CLASSROOM_REQUEST_FAILED;

// To unenrol from a classroom
export const UNENROL_INTO_CLASSROOM_REQUEST_SENT = 'UNENROL_INTO_CLASSROOM_REQUEST_SENT';
export type T_UNENROL_INTO_CLASSROOM_REQUEST_SENT = typeof UNENROL_INTO_CLASSROOM_REQUEST_SENT;

export const UNENROL_INTO_CLASSROOM_REQUEST_SUCCESS = 'UNENROL_INTO_CLASSROOM_REQUEST_SUCCESS';
export type T_UNENROL_INTO_CLASSROOM_REQUEST_SUCCESS = typeof UNENROL_INTO_CLASSROOM_REQUEST_SUCCESS;

export const UNENROL_INTO_CLASSROOM_REQUEST_FAILED = 'UNENROL_INTO_CLASSROOM_REQUEST_FAILED';
export type T_UNENROL_INTO_CLASSROOM_REQUEST_FAILED = typeof UNENROL_INTO_CLASSROOM_REQUEST_FAILED;